# Generated by Django 4.2.30 on 2026-07-03 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_patientprofile_doctorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('text', models.TextField(help_text="Patient's review text")),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews appear on the Home Page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointment.takeappointment')),
            ],
            options={
                'verbose_name': 'Patient Review',
                'verbose_name_plural': 'Patient Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
