# Generated by Django 4.2.30 on 2026-07-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
