# Generated by Django 4.2.30 on 2026-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_takeappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_days',
            field=models.CharField(blank=True, help_text='Comma separated working days, e.g. Monday, Wednesday', max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.CharField(blank=True, help_text='e.g. 175 cm or 5\'9"', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 70 kg', max_length=10),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
    ]
