# Generated by Django 4.2.30 on 2026-07-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0006_doctorprofile_license_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_notes', models.TextField(blank=True, help_text="Doctor's diagnosis notes")),
                ('advice', models.TextField(blank=True, help_text='General medical advice')),
                ('lab_tests', models.TextField(blank=True, help_text='Recommended lab tests')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='meeting_provider',
            field=models.CharField(blank=True, choices=[('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('meet', 'Google Meet')], default='jitsi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Jitsi/Zoom/Meet link for online consultation', null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Three Times Daily'), ('four_times', 'Four Times Daily'), ('as_needed', 'As Needed (SOS)'), ('weekly', 'Once Weekly'), ('custom', 'Custom')], default='twice_daily', max_length=20)),
                ('duration', models.CharField(help_text='e.g. 7 days, 2 weeks', max_length=100)),
                ('instructions', models.CharField(blank=True, help_text='e.g. Take after meals', max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointment.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointment.takeappointment'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('upi', 'UPI'), ('cash', 'Cash')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointment.takeappointment')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test / CBC'), ('urine_report', 'Urine Report'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('xray', 'X-Ray'), ('ecg', 'ECG / EKG'), ('prescription', 'Prescription'), ('liver_function', 'Liver Function Test'), ('kidney_function', 'Kidney Function Test'), ('thyroid', 'Thyroid Panel'), ('lipid_profile', 'Lipid Profile'), ('other', 'Other Report')], default='other', max_length=30)),
                ('file', models.FileField(help_text='Accepted: PDF, PNG, JPG, JPEG', upload_to='medical_reports/%Y/%m/')),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional patient notes')),
                ('extracted_text', models.TextField(blank=True, help_text='OCR/PDF-extracted raw text')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of findings')),
                ('ai_findings', models.TextField(blank=True, help_text='AI-highlighted abnormal/normal values')),
                ('ai_recommendation', models.TextField(blank=True, help_text='AI suggested next steps')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing...'), ('done', 'Analysis Complete'), ('failed', 'Analysis Failed'), ('no_text', 'No Text Extracted')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
