# Generated by Django 4.2.30 on 2026-07-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0008_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed about section for public profile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_covers/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='social_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('quit', 'Quit')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_covers/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='exercise',
            field=models.CharField(blank=True, choices=[('none', 'Sedentary'), ('light', 'Light (1-2x/week)'), ('moderate', 'Moderate (3-4x/week)'), ('active', 'Very Active (5+/week)')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer Not to Say')], max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoking',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('ex_smoker', 'Ex-Smoker')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='surgeries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='cancellation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('schedule_conflict', 'Schedule Conflict'), ('found_another_doctor', 'Found Another Doctor'), ('recovered', 'Recovered'), ('emergency', 'Emergency'), ('financial', 'Financial Reasons'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_card', models.FileField(blank=True, null=True, upload_to='patient_insurance/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='appointment.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Insurance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('friend', 'Friend'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='appointment.patientprofile')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='DoctorVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('holiday', 'Holiday'), ('emergency', 'Emergency Leave'), ('conference', 'Conference / Training'), ('personal', 'Personal Leave'), ('recurring', 'Recurring Leave')], default='holiday', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_recurring_weekly', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Vacation',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 5 PM)'), ('evening', 'Evening (5 PM – 9 PM)'), ('night', 'Night (9 PM – 12 AM)')], default='morning', max_length=20)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Max patients per slot')),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False, help_text='Video consultation slot')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Slot',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. MBBS, MD, MS', max_length=50)),
                ('institute', models.CharField(help_text='Institution name', max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year of completion', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Qualification',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DoctorFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('AED', 'د.إ UAE Dirham')], default='INR', max_length=5)),
                ('clinic_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('video_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('emergency_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('followup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)')),
                ('free_followup_days', models.PositiveIntegerField(default=0, help_text='Free follow-up within N days')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Fee Structure',
            },
        ),
        migrations.CreateModel(
            name='DoctorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('description', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('license', 'Medical License'), ('degree', 'Degree Certificate'), ('govt_id', 'Government ID'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='doctor_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('admin_notes', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clinic_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('online', 'Online Consultation')], default='clinic', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('working_days', models.CharField(blank=True, help_text='Comma-separated day codes: Mon,Wed,Fri', max_length=100)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='appointment.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Clinic',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='appointment.doctorslot')),
                ('take_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_booking', to='appointment.takeappointment')),
            ],
            options={
                'verbose_name': 'Slot Booking',
                'ordering': ['-booking_date'],
                'unique_together': {('slot', 'patient', 'booking_date')},
            },
        ),
    ]
