# Generated by Django 4.2.30 on 2026-07-09 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0009_doctorprofile_about_doctorprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor_reply',
            field=models.TextField(blank=True, help_text="Doctor's reply/response to the patient review", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='doctor_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_users',
            field=models.ManyToManyField(blank=True, help_text='Users who found this review helpful', related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
