# Generated by Django 4.2.30 on 2026-07-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0011_payment_refund_reason_payment_refund_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Medical diagnosis'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_qrs/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Patient's symptoms"),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='afternoon',
            field=models.BooleanField(default=False, help_text='Take in afternoon'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='before_food',
            field=models.BooleanField(default=False, help_text='Take before food'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='morning',
            field=models.BooleanField(default=False, help_text='Take in morning'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='night',
            field=models.BooleanField(default=False, help_text='Take at night'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Specific notes for this medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days to take medicine'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='Doctor notes logged during meeting', null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='meeting_status',
            field=models.CharField(choices=[('waiting', 'Waiting Room'), ('active', 'Active Call'), ('ended', 'Ended')], default='waiting', help_text='Status of the tele-consultation meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 7 days, 2 weeks', max_length=100),
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting_files/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_files', to='appointment.takeappointment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting File',
                'verbose_name_plural': 'Meeting Files',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='appointment.takeappointment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Chat Message',
                'verbose_name_plural': 'Meeting Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
