# Generated by Django 4.2.30 on 2026-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_voicesummary_prediction_medicine_labvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/additional/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time_slots',
            field=models.CharField(blank=True, help_text='Available time slots e.g. 09:00 AM - 05:00 PM', max_length=250),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='certificates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/degree/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='govt_id_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/govt_id/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/license/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_council',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='previous_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='super_specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
