# Generated by Django 4.2.30 on 2026-08-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0014_doctorprofile_additional_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_qualification_certificates',
            field=models.FileField(blank=True, help_text='Upload MD/MS/DM/MCh or other postgraduate certificates', null=True, upload_to='doctor_documents/additional_qualifications/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='govt_photo_id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card')], help_text='Type of government-issued photo ID uploaded', max_length=30),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='mbbs_degree_certificate',
            field=models.FileField(blank=True, help_text='Upload MBBS degree certificate (PDF/JPG/PNG, max 10MB)', null=True, upload_to='doctor_documents/mbbs/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_council_registration_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of registration with state medical council', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='nmc_registration_number',
            field=models.CharField(blank=True, help_text='NMC Registration Number (mandatory for verification)', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Recent selfie/profile photo for identity verification', null=True, upload_to='doctor_documents/selfie/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state_medical_council',
            field=models.CharField(blank=True, help_text='e.g. Maharashtra Medical Council, Delhi Medical Council', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when verification decision was made', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_method',
            field=models.CharField(blank=True, default='manual', help_text='Verification method: manual, nmc_api, digilocker, qr_code', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_remarks',
            field=models.TextField(blank=True, help_text='Admin remarks on the verification decision (visible to doctor)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staff who approved or rejected this doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Documents Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
