# Generated by Django 4.2.30 on 2026-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_simplify_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique Doctor ID (e.g. DOC20260001)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='nmc_certificate_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique NMC Certificate Number (e.g. NMC-2026-000001)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_id',
            field=models.CharField(blank=True, help_text='Auto-generated unique Registration ID (e.g. REG-2026-000001)', max_length=100, null=True, unique=True),
        ),
    ]
