# Generated by Django 4.2.30 on 2026-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_add_doctor_approval_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for this appointment (used to cancel on appointment cancellation).', max_length=255, null=True),
        ),
    ]
