# Generated by Django 4.2.30 on 2026-08-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_payment_paid_at_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='google_calendar_connected',
            field=models.BooleanField(default=False, help_text='True if doctor has connected Google Calendar via OAuth'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='google_calendar_credentials',
            field=models.TextField(blank=True, help_text='Encrypted Google OAuth 2.0 refresh & access tokens for Google Calendar API', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='google_calendar_email',
            field=models.CharField(blank=True, help_text='Email address of the connected Google Calendar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='appointment_date',
            field=models.DateField(blank=True, help_text='Date of appointment', null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='appointment_end_time',
            field=models.TimeField(blank=True, help_text='End time of appointment', null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='appointment_start_time',
            field=models.TimeField(blank=True, help_text='Start time of appointment', null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='calendar_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('not_connected', 'Calendar Not Connected')], default='pending', help_text='Google Calendar synchronization status', max_length=20),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Alias for Google Calendar event ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Generated Google Meet conference URL from Google Calendar API', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, help_text='24-hour reminder sent flag'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False, help_text='2-hour reminder sent flag'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Timezone for appointment calculation', max_length=50),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for this appointment (used to update/cancel event).', max_length=255, null=True),
        ),
    ]
