# Generated by Django 4.2.30 on 2026-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_doctorprofile_google_calendar_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_16h_sent',
            field=models.BooleanField(default=False, help_text='16-hour reminder sent flag'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_30m_sent',
            field=models.BooleanField(default=False, help_text='30-minute reminder sent flag'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_4h_sent',
            field=models.BooleanField(default=False, help_text='4-hour reminder sent flag'),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='reminder_8h_sent',
            field=models.BooleanField(default=False, help_text='8-hour reminder sent flag'),
        ),
    ]
