# Generated by Django 4.2.30 on 2026-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phoneotp_user_username_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device/browser token for push notifications.', max_length=512, null=True),
        ),
    ]
