import os
import logging
from django.conf import settings

logger = logging.getLogger(__name__)

class BaseLLMConnector:
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        raise NotImplementedError("Subclasses must implement generate_response")

class GeminiConnector(BaseLLMConnector):
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        try:
            from ai.services.gemini import GeminiClient
            client = GeminiClient()
            return client.generate_content(prompt, context=context, system_instruction=system_prompt)
        except Exception as e:
            logger.error(f"Gemini generation error: {e}")
            return self._mock_response(prompt)

    def _mock_response(self, prompt: str) -> str:
        return f"[Mock Gemini Response] Thank you for your inquiry. This is a placeholder AI response for prompt: '{prompt[:40]}...'"

class OpenAIConnector(BaseLLMConnector):
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        api_key = getattr(settings, 'OPENAI_API_KEY', os.environ.get('OPENAI_API_KEY', ''))
        if not api_key or api_key == 'YOUR_OPENAI_API_KEY':
            return self._mock_response(prompt)
        try:
            # Placeholder for real openai client integration
            # import openai
            # client = openai.OpenAI(api_key=api_key)
            # response = client.chat.completions.create(...)
            return "[OpenAI Connection Success] Response generated by OpenAI."
        except Exception as e:
            logger.error(f"OpenAI error: {e}")
            return self._mock_response(prompt)

    def _mock_response(self, prompt: str) -> str:
        return f"[Mock OpenAI Response] Received: '{prompt[:40]}...'"

class ClaudeConnector(BaseLLMConnector):
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        api_key = getattr(settings, 'CLAUDE_API_KEY', os.environ.get('CLAUDE_API_KEY', ''))
        if not api_key or api_key == 'YOUR_CLAUDE_API_KEY':
            return self._mock_response(prompt)
        try:
            return "[Claude Connection Success] Response generated by Claude."
        except Exception as e:
            logger.error(f"Claude error: {e}")
            return self._mock_response(prompt)

    def _mock_response(self, prompt: str) -> str:
        return f"[Mock Claude Response] Received: '{prompt[:40]}...'"

class OllamaConnector(BaseLLMConnector):
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        host = getattr(settings, 'OLLAMA_HOST', os.environ.get('OLLAMA_HOST', 'http://localhost:11434'))
        # Try local Ollama connection
        try:
            import requests
            response = requests.post(f"{host}/api/generate", json={"model": "llama2", "prompt": prompt}, timeout=2)
            if response.status_code == 200:
                return response.json().get('response', '')
        except Exception:
            pass
        return f"[Mock Ollama Llama2 Response] Locally processed prompt: '{prompt[:40]}...'"

class HuggingFaceConnector(BaseLLMConnector):
    def generate_response(self, prompt: str, system_prompt: str = "", context: str = "") -> str:
        api_key = getattr(settings, 'HF_API_KEY', os.environ.get('HF_API_KEY', ''))
        if not api_key:
            return self._mock_response(prompt)
        try:
            return "[HuggingFace Connection Success] Model response generated."
        except Exception as e:
            return self._mock_response(prompt)

    def _mock_response(self, prompt: str) -> str:
        return f"[Mock HuggingFace Response] Processed: '{prompt[:40]}...'"

class LLMManager:
    @staticmethod
    def get_connector(provider: str = 'gemini') -> BaseLLMConnector:
        providers = {
            'gemini': GeminiConnector,
            'openai': OpenAIConnector,
            'claude': ClaudeConnector,
            'ollama': OllamaConnector,
            'huggingface': HuggingFaceConnector
        }
        connector_class = providers.get(provider.lower(), GeminiConnector)
        return connector_class()
